# Generated by Django 2.0.7 on 2018-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('author_id', models.IntegerField(unique=True, verbose_name='author id')),
                ('matriculation_id', models.IntegerField(null=True, verbose_name='matriculation id')),
                ('profile_url', models.URLField(null=True, verbose_name='url_field')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('party', models.CharField(max_length=255, null=True, verbose_name='party')),
                ('state', models.CharField(max_length=255, null=True, verbose_name='state')),
                ('mandate_id', models.IntegerField(null=True, verbose_name='mandate it')),
                ('photo_url', models.URLField(null=True, verbose_name='photo url')),
                ('gender', models.CharField(max_length=255, null=True, verbose_name='gender')),
                ('legal_name', models.CharField(max_length=255, null=True, verbose_name='legal name')),
                ('phone_number', models.CharField(max_length=255, null=True, verbose_name='phone #')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('cpf', models.CharField(max_length=255, null=True, verbose_name='cpf')),
                ('birth_city', models.CharField(max_length=255, null=True, verbose_name='birth city')),
                ('birth_state', models.CharField(max_length=255, null=True, verbose_name='birth state')),
                ('birh_date', models.DateField(null=True, verbose_name='birth date')),
                ('scholarity', models.CharField(max_length=255, null=True, verbose_name='scholarity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Congressman',
                'verbose_name_plural': 'Congressmen',
                'ordering': ('name',),
            },
        ),
    ]
