# Generated by Django 2.0.7 on 2018-07-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255, verbose_name='session type')),
                ('phase', models.CharField(max_length=255, verbose_name='phase')),
                ('summary', models.TextField(verbose_name='summary')),
                ('pronounced_at', models.DateTimeField(verbose_name='when')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discourses', to='core.Congressman')),
            ],
            options={
                'verbose_name': 'Discourse',
                'verbose_name_plural': 'Discourses',
                'ordering': ('congressman__name',),
            },
        ),
    ]
