# Generated by Django 2.0.7 on 2018-07-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='code')),
                ('url', models.URLField(null=True, verbose_name='URL')),
                ('file_url', models.URLField(null=True, verbose_name='file url')),
                ('summary', models.TextField(null=True, verbose_name='summary')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='status')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='type')),
                ('accessory_of', models.IntegerField(null=True, verbose_name='accessory of')),
                ('full_content', models.TextField(null=True, verbose_name='full content')),
                ('proposed_at', models.DateField(null=True, verbose_name='started at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('congressmen', models.ManyToManyField(null=True, related_name='propositions', to='core.Congressman')),
            ],
            options={
                'verbose_name': 'Proposition',
                'verbose_name_plural': 'Propositions',
                'ordering': ('-proposed_at', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=255, verbose_name='session code')),
                ('session_date', models.DateField(verbose_name='session date')),
                ('vote', models.CharField(max_length=255, verbose_name='vote')),
                ('presence', models.CharField(max_length=255, verbose_name='presence')),
                ('absence_reason', models.CharField(max_length=255, null=True, verbose_name='absence reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Congressman')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proposition')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ('-session_date', 'session_code'),
            },
        ),
        migrations.AddField(
            model_name='proposition',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', through='core.Vote', to='core.Congressman'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('congressman', 'proposition', 'session_date')},
        ),
    ]
