# Generated by Django 2.0.7 on 2018-07-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180729_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='congressmen',
            field=models.ManyToManyField(blank=True, related_name='propositions', to='core.Congressman'),
        ),
    ]
