# Generated by Django 2.0.7 on 2018-07-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180729_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(max_length=255, null=True, verbose_name='vote'),
        ),
    ]
