# Generated by Django 2.0.7 on 2018-07-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180730_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressman',
            name='registration_id',
            field=models.IntegerField(null=True, verbose_name='registration id'),
        ),
    ]
