# Generated by Django 2.0.7 on 2018-07-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_congressman_registration_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposition',
            options={'ordering': ('-proposed_at',), 'verbose_name': 'Proposition', 'verbose_name_plural': 'Propositions'},
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='accessory_of',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='code',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='type',
        ),
        migrations.AddField(
            model_name='proposition',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='subject',
            field=models.CharField(max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='type_code',
            field=models.CharField(max_length=255, null=True, verbose_name='type code'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='type_name',
            field=models.CharField(max_length=255, null=True, verbose_name='type name'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='proposed_at',
            field=models.DateTimeField(null=True, verbose_name='started at'),
        ),
    ]
