# Generated by Django 2.0.7 on 2018-07-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180730_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='detailed_summary',
            field=models.TextField(null=True, verbose_name='detailed summary'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='number',
            field=models.CharField(max_length=255, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='year',
            field=models.IntegerField(null=True, verbose_name='year'),
        ),
    ]
