# Generated by Django 2.0.7 on 2018-07-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180730_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='numberer_code',
            field=models.CharField(max_length=255, null=True, verbose_name='numberer code'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='numberer_name',
            field=models.CharField(max_length=255, null=True, verbose_name='numberer name'),
        ),
    ]
