# Generated by Django 2.0.7 on 2018-07-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180730_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='numberer_name',
            field=models.TextField(null=True, verbose_name='numberer name'),
        ),
    ]
