# Generated by Django 2.0.7 on 2018-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180730_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True, verbose_name='tag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('propositions', models.ManyToManyField(blank=True, related_name='tags', to='core.Proposition')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('tag',),
            },
        ),
    ]
